spring:
  application:
    name: ai-code-helper
  profiles:
    active: local
server:
  port: 8081
  servlet:
    context-path: /api
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: <your-qwen-api-key> # 通义千问的 key
      streaming-chat-model:
        model-name: qwen-max
        api-key: <your-qwen-api-key> # 通义千问的 key
      embedding-model:
        model-name: text-embedding-v4
        api-key: <your-qwen-api-key> # 通义千问的 key
bigmodel:
  api-key: <your-bigmodel-api-key> # 智谱的 key